# Generated by Django 2.2.6 on 2021-08-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
